---
- name: restart machine
  shell: sleep 2 && shutdown -r +1 "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  listen: restart server

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=30
  listen: restart server

- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted

- name: restart ntp
  systemd:
     name: ntpd
     state: restarted
     enabled: yes
...
