---
- hosts: antee-test-local 
  remote_user:  root
  vars_prompt:
     - name: "mysql_password"
       prompt: "Set mysql-wide password "
       default: "toor"
       private: yes
     - name: "new_sys_user"
       prompt: "Set name of new system user "
       default: "franta"
       private: no

  roles:
    - ubuntu_inic
...
