---

- name: restart apache
  systemd: 
    name: apache2
    state: restarted
    enabled: yes
    
- name: restart mysql
  systemd:
          name: mysql
          state: restarted
          enabled: yes
          
...