---

- name: disable modules
  apache2_module:
     name: php7.0
     state: absent
     
- name: enable modules
  apache2_module:
     name: "{{ item }}"
     state: present
  with_items: "{{ enabled_apache_modules }}"
  notify: restart apache
    
- name: symlink apache modes
  file: 
    src: /usr/bin/php5.6
    dest: /etc/alternatives/php
    state: link
    force: yes
    
- name: edit virtualhost
  blockinfile:
    path: /etc/apache2/sites-available/000-default.conf
    insertafter: "<VirtualHost *:80>"
    block: |
      ServerName localhost
       " <Directory /home/{{ new_sys_user }}/.www>"
           Options Indexes FollowSymLinks MultiViews
           Require all granted
           AllowOverride All
        </Directory>
        
- name: edit apache2.conf
  lineinfile:
    path: /etc/apache2/apache2.conf
    insertafter: "Global configuration"
    line: "ServerName localhost"
    state: present
  notify: restart apache
    
- name: edit apache sites available
  lineinfile: 
    path: /etc/apache2/sites-available/000-default.conf
    line: "VirtualDocumentRoot /home/{{ new_sys_user }}/.www/%0"
    state: present
    insertbefore: BOF

- name: create local.ini
  template:
    src: local.ini.j2
    dest: /etc/php/5.6/mods-available/local.ini

- name: symlink local.ini
  file:
    src: /etc/php/5.6/mods-available/local.ini
    dest: "{{ item }}"
    state: link
    force: yes
  with_items:
    - /etc/php/5.6/apache2/conf.d/20-local.ini
    - /etc/php/5.6/cli/conf.d/20-local.ini

...
