---
- name: create group
  group:
          name: "{{ new_sys_user }}"
          state: present 
- name: create new user
  user:
          name: "{{ new_sys_user }}"
          createhome: yes
          generate_ssh_key: yes
          group: "{{ new_sys_user }}"
          groups: users, sudo
          shell: /bin/bash
          system: yes
          update_password: on_create

- name: add php repository
  apt_repository:
          repo: "ppa:ondrej/php"

- name: install all packages
  apt:
          name: "{{ item }}"
          state: latest
          update_cache: yes
  with_items: "{{ deps }}"
- name: pip install
  pip:
       name: '{{ item }}'
  with_items:
        - pexpect
        - mysql-connector-python
        - MySQL-python
       
- name: create dirs
  file:
          path: "{{ item }}"
          state: directory
          recurse: yes
  with_items: "{{ home_dirs }}"

- include_tasks: mysql_inic.yml

- include_tasks: conf_apache.yml

- include_tasks: npm_install.yml

- include_tasks: edit_hosts.yml

- name: fakemail setup
  copy:
    src: fakemail 
    dest: /home/{{ new_sys_user }}/fakemail
    mode: 0775
    owner: "{{ new_sys_user }}"
    group: "{{ new_sys_user }}"

- include_tasks: ipo_setup.yml    
...
