---
- name: restart mysql
  systemd:
          name: mysql
          state: started 
          enabled: yes

- name: create my.cnf
  file:
     path: /root/.my.cnf
     state: touch
- name: insert headers to hosts
  blockinfile:
      path: /root/.my.cnf
      block: |
       [client]
       user=root
       password={{ mysql_password }}
- name: Sets the root password
  mysql_user: 
       user: root 
       password: "{{ mysql_password }}" 
       host: localhost
- name: insert password to mysql
  lineinfile:
     dest: /root/.my.cnf
     regexp: '^password='
     line: "password={{mysql_password}}"
- name: Delete anonymous MySQL server user for localhost
  mysql_user: user="" state=absent
- name: Secure the MySQL root user for IPV6 localhost (::1)
  mysql_user: 
      user: "root" 
      password: "{{ mysql_password }}" 
      host: "::1"
- name: Secures the MySQL root user for IPV4 localhost (127.0.0.1)
  mysql_user: 
      user: "root" 
      password: "{{ mysql_password }}" 
      host: "127.0.0.1"
- name: Secures the MySQL root user for localhost domain (localhost)
  mysql_user: 
      user: "root" 
      password: "{{ mysql_password }}" 
      host: "localhost"
- name: Secures the MySQL root user for server_hostname domain
  mysql_user: 
      user: "root" 
      password: "{{ mysql_password }}" 
      host: db
- name: Create a database
  mysql_db: name=test collation=utf8_general_ci encoding=utf8 state=present
  notify: restart mysql
  
- name: set group concat variable
  mysql_variables: 
    variable: group_concat_max_len
    value: 100000
  notify: restart mysql

- name: get version of mysql
  shell: mysql --version
  register: mysql_version

- name: edit mysql.cnf
  blockinfile:
    path: /etc/mysql/conf.d/mysql.cnf
    block: |
      [mysqld]
      sql_mode = "ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
      group_concat_max_len=100000

- name: add db
  mysql_db:
    name: ipo
    state: present

- name: add new user
  mysql_user:
    name: admin
    host: 200.0.0.2
    priv: 'ipo.*:ALL,GRANT'
    state: present

...  
