---

   - name: stop spamassassin
     service: name=spamassassin state=stopped
   - name: disable spamassassin
     shell: systemctl disable spamassassin

   - name: make link
     file:
      src: /usr/lib/x86_64-linux-gnu/libc-client.a
      dest: /usr/lib/libc-client.a
   - name: copy postfix conf
     blockinfile:
      path: /etc/postfix/master.cf
      insertafter: "submission"
      content: |
        submission inet n - - - - smtpd
         -o syslog_name=postfix/submission
         -o smtpd_tls_security_level=encrypt
         -o smtpd_sasl_auth_enable=yes
         -o smtpd_client_restrictions=permit_sasl_authenticated,reject
        smtps inet n - - - - smtpd
         -o syslog_name=postfix/smtps
         -o smtpd_tls_wrappermode=yes
         -o smtpd_sasl_auth_enable=yes
         -o smtpd_client_restrictions=permit_sasl_authenticated,reject
   - name: restart postfix
     service: name=postfix state=restarted

...